[package]
name = "specs-physics"
version = "0.3.0"
authors = ["Benjamin Amling <benjamin@amling.net>", "Kel <x@unclear.info>", "jojolepro <jojolepromain@gmail.com>"]
repository = "https://github.com/amethyst/specs-physics.git"
homepage = "https://github.com/amethyst/specs-physics.git"
edition = "2018"

license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/specs-physics"
description = "nphysics integration for the Specs entity component system"

keywords = ["specs", "nphysics", "nphysics3d"]

[features]
physics3d = ["ncollide3d", "nphysics3d"]
physics2d = ["ncollide2d", "nphysics2d"]
amethyst = ["amethyst_core"]

[dependencies]
log = "^0.4.6"
specs = "^0.14"
specs-hierarchy = "^0.3"
shrev = "^1.0"
nalgebra = "^0.18"
ncollide2d = { version = "^0.19", optional = true }
ncollide3d = { version = "^0.19", optional = true }
nphysics2d = { version = "^0.11", optional = true }
nphysics3d = { version = "^0.11", optional = true }
amethyst_core = { version = "^0.7", optional = true }
objekt = "0.1.2"

[dev-dependencies]
simple_logger = "1.2.0"
approx = "0.3.2"

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["physics3d"]

[[example]]
name = "hierarchy"
path = "examples/hierarchy.rs"
required-features = ["physics3d"]

[[example]]
name = "positions"
path = "examples/positions.rs"
required-features = ["physics3d"]

[[example]]
name = "collision"
path = "examples/collision.rs"
required-features = ["physics3d"]

[[example]]
name = "events"
path = "examples/events.rs"
required-features = ["physics3d"]

