[package]
name = "specs-physics"
version = "0.2.2"
authors = ["Benjamin Amling <benjamin@amling.net>"]
repository = "https://github.com/bamling/specs-physics.git"
homepage = "https://github.com/bamling/specs-physics.git"
edition = "2018"

license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/specs-physics"
description = "nphysics integration for the Specs entity component system"

keywords = ["specs", "nphysics", "nphysics3d"]

[features]
default = []

[dependencies]
log = "0.4.6"
specs = "0.14.3"
specs-hierarchy = "0.3.1"
shrev = "1.1.1"
nalgebra = "0.18.0"
ncollide3d = "0.19.1"
nphysics3d = "0.11.1"
amethyst_core = { version = "0.6.0", optional = true }

[dev-dependencies]
simple_logger = "1.2.0"

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "hierarchy"
path = "examples/hierarchy.rs"

[[example]]
name = "positions"
path = "examples/positions.rs"

[[example]]
name = "collision"
path = "examples/collision.rs"

[[example]]
name = "events"
path = "examples/events.rs"

